import type { Metadata } from "next";

import "./globals.css";
import Layout from "@/components/layout/Layout";
import localFont from "next/font/local"



const lalezar = localFont({
  src : '../../public/fonts/Lalezar-Regular.ttf'
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={lalezar.className}>
        <Layout>

        {children}
        </Layout>
      </body>
    </html>
  );
}
